# Generated by Django 4.1.3 on 2022-12-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthenticate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarioieb',
            old_name='username',
            new_name='user',
        ),
    ]
