# Generated by Django 4.1.3 on 2022-12-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthenticate', '0002_wireline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wireline',
            name='ampacity',
            field=models.DecimalField(decimal_places=16, max_digits=16),
        ),
        migrations.AlterField(
            model_name='wireline',
            name='new_current',
            field=models.DecimalField(decimal_places=16, max_digits=16),
        ),
        migrations.AlterField(
            model_name='wireline',
            name='new_diameter',
            field=models.DecimalField(decimal_places=16, max_digits=16),
        ),
        migrations.AlterField(
            model_name='wireline',
            name='new_thickness',
            field=models.DecimalField(decimal_places=16, max_digits=16),
        ),
        migrations.AlterField(
            model_name='wireline',
            name='new_voltage',
            field=models.DecimalField(decimal_places=16, max_digits=16),
        ),
    ]
