# Generated by Django 4.1.3 on 2022-12-11 19:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserAuthenticate', '0002_rename_username_usuarioieb_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsuarioIEB',
            new_name='IEBUsuarios',
        ),
    ]
