# Generated by Django 4.1.3 on 2022-12-11 19:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserAuthenticate', '0003_rename_usuarioieb_iebusuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IEBUsuarios',
            new_name='Usuario',
        ),
    ]
