# Generated by Django 4.1.3 on 2022-12-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthenticate', '0003_alter_wireline_ampacity_alter_wireline_new_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wireline',
            name='ampacity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wireline',
            name='new_current',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wireline',
            name='new_diameter',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wireline',
            name='new_thickness',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wireline',
            name='new_voltage',
            field=models.FloatField(),
        ),
    ]
