# Generated by Django 4.1.3 on 2022-12-15 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthenticate', '0004_alter_wireline_ampacity_alter_wireline_new_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyect',
            name='nmproy',
            field=models.CharField(max_length=64, verbose_name='Nombre Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='typroy',
            field=models.CharField(max_length=64, verbose_name='Tipo Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='wireline',
            name='ampacity',
            field=models.FloatField(verbose_name='Ampacidad'),
        ),
        migrations.AlterField(
            model_name='wireline',
            name='material',
            field=models.CharField(max_length=128, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='wireline',
            name='new_current',
            field=models.FloatField(verbose_name='Corriente*'),
        ),
        migrations.AlterField(
            model_name='wireline',
            name='new_diameter',
            field=models.FloatField(verbose_name='Diametro*'),
        ),
        migrations.AlterField(
            model_name='wireline',
            name='new_thickness',
            field=models.FloatField(verbose_name='Espesor*'),
        ),
        migrations.AlterField(
            model_name='wireline',
            name='new_voltage',
            field=models.FloatField(verbose_name='Tension*'),
        ),
    ]
