# Generated by Django 4.1.3 on 2022-12-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthenticate', '0005_rename_user_usuario_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='user',
        ),
    ]
