# Generated by Django 4.1.3 on 2022-12-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthenticate', '0005_alter_proyect_nmproy_alter_proyect_typroy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavesProyects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savename', models.CharField(max_length=128, unique=True, verbose_name='Seleccion')),
                ('username', models.CharField(max_length=128, verbose_name='Usuario')),
                ('nmproy', models.CharField(max_length=128, verbose_name='NmProyecto')),
                ('current', models.FloatField(verbose_name='Ampacidad')),
                ('voltage', models.FloatField(verbose_name='Tension*')),
                ('ampacity', models.FloatField(verbose_name='Espesor*')),
                ('new_current', models.FloatField(verbose_name='Diametro*')),
                ('datenow', models.DateField()),
            ],
            options={
                'verbose_name': 'Seleccion',
                'verbose_name_plural': 'Selecciones',
            },
        ),
        migrations.AlterModelOptions(
            name='proyect',
            options={'verbose_name': 'Asignacion', 'verbose_name_plural': 'Asignaciones'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='wireline',
            options={'verbose_name': 'Catalogo', 'verbose_name_plural': 'Catalogo'},
        ),
        migrations.AlterField(
            model_name='proyect',
            name='nmproy',
            field=models.CharField(max_length=64, verbose_name='Nm-Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='typroy',
            field=models.CharField(max_length=64, verbose_name='Ty-Proyecto'),
        ),
    ]
