# Generated by Django 4.1.3 on 2022-12-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthenticate', '0006_savesproyects_alter_proyect_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savesproyects',
            name='message',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='savesproyects',
            name='ampacity',
            field=models.FloatField(verbose_name='Ampacidad'),
        ),
        migrations.AlterField(
            model_name='savesproyects',
            name='current',
            field=models.FloatField(verbose_name='Corriente'),
        ),
        migrations.AlterField(
            model_name='savesproyects',
            name='datenow',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='savesproyects',
            name='new_current',
            field=models.FloatField(verbose_name='Corriente*'),
        ),
        migrations.AlterField(
            model_name='savesproyects',
            name='nmproy',
            field=models.CharField(max_length=128, verbose_name='Nm-Proyecto'),
        ),
        migrations.AlterField(
            model_name='savesproyects',
            name='voltage',
            field=models.FloatField(verbose_name='Tension'),
        ),
    ]
