# Generated by Django 4.1.3 on 2022-12-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthenticate', '0007_savesproyects_message_alter_savesproyects_ampacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wireline',
            options={'verbose_name': 'Cable', 'verbose_name_plural': 'Catalogo'},
        ),
        migrations.AlterField(
            model_name='savesproyects',
            name='savename',
            field=models.CharField(max_length=128, verbose_name='Seleccion'),
        ),
    ]
